#!/usr/bin/env bash

SESSION=${1?Error: No Session Given}

if [ $SESSION = "cisc210" ]
then
    ssh carlsonc@cisc210.cis.udel.edu
fi

if [ $SESSION = "go" ]
then
    ssh carlsonc@go.eecis.udel.edu
fi
